/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#002113',
        'secondary-fixed-dim': '#c8c6c5',
        'surface-container-high': '#272a2c',
        'surface-container': '#1d2022',
        'tertiary-fixed-dim': '#adc6ff',
        'inverse-on-surface': '#2d3133',
        'on-primary-fixed-variant': '#005236',
        secondary: '#c8c6c5',
        primary: '#4edea3',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#323537',
        'on-tertiary-container': '#00367a',
        'on-error': '#690005',
        'surface-container-low': '#191c1e',
        'secondary-fixed': '#e5e2e1',
        'inverse-surface': '#e0e3e5',
        'on-surface': '#e0e3e5',
        error: '#ffb4ab',
        'surface-container-lowest': '#0b0f10',
        'surface-tint': '#4edea3',
        'on-tertiary-fixed': '#001a42',
        'surface-dim': '#101415',
        outline: '#86948a',
        'surface-bright': '#363a3b',
        'on-primary': '#003824',
        tertiary: '#adc6ff',
        'on-tertiary': '#002e6a',
        'on-secondary-fixed': '#1c1b1b',
        'on-primary-container': '#00422b',
        'on-secondary-fixed-variant': '#474646',
        'primary-container': '#10b981',
        'primary-fixed-dim': '#4edea3',
        background: '#101415',
        'surface-variant': '#323537',
        'on-tertiary-fixed-variant': '#004395',
        'tertiary-fixed': '#d8e2ff',
        'on-secondary-container': '#bab8b7',
        'error-container': '#93000a',
        'outline-variant': '#3c4a42',
        'on-secondary': '#313030',
        surface: '#101415',
        'on-surface-variant': '#bbcabf',
        'primary-fixed': '#6ffbbe',
        'inverse-primary': '#006c49',
        'secondary-container': '#4a4949',
        'tertiary-container': '#71a1ff',
        'on-background': '#e0e3e5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  spacing: {
    'sidebar-width': '320px',
    'message-gap': '4px',
    base: '8px',
    'info-panel-width': '360px',
    'container-padding-desktop': '24px',
    'thread-gap': '12px',
    'container-padding-mobile': '16px',
  },
  fontFamily: {
    'label-md': ['Manrope'],
    'headline-md': ['Manrope'],
    'headline-lg-mobile': ['Manrope'],
    'headline-lg': ['Manrope'],
    'label-xs': ['Manrope'],
    'body-lg': ['Manrope'],
    'body-sm': ['Manrope'],
  },
  fontSize: {
    'label-md': ['13px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '600' }],
    'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
    'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
    'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
    'label-xs': ['11px', { lineHeight: '1', fontWeight: '500' }],
    'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
    'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
  },
  plugins: [],
};