worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    include /etc/nginx/conf.d/upstreams.conf;
    include /etc/nginx/conf.d/websocket_upgrade.conf;

    server {
        listen: 80;
        server_name localhost;

        include /etc/nginx/conf.d/auth.conf;
        include /etc/nginx/conf.d/admin.conf;
        include /etc/nginx/conf.d/chat.conf;

    }
}